# Generated by Django 3.0.7 on 2021-01-16 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portFolio1App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 16, 11, 11, 33, 540788, tzinfo=utc)),
        ),
    ]
