# Generated by Django 3.0.7 on 2021-01-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portFolio1App', '0002_news_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
    ]
